<?php

declare(strict_types=1);

namespace Shamimstack\YouTubeCloudStorage\DTOs;

/**
 * Immutable Data Transfer Object representing a single fountain-coded symbol packet.
 *
 * Each packet is embedded into video frames via sign-bit nudging of DCT coefficients.
 * The structure is:
 *   [Block ID: 4 bytes] [Payload: N bytes] [CRC32: 4 bytes]
 *
 * The CRC32 checksum covers both the Block ID and Payload fields, enabling
 * the decoder to detect corruption introduced by YouTube's lossy re-encoding.
 *
 * Mathematical context:
 *   - Wirehair generates packets with sequential block IDs starting from 0.
 *   - The first N packets (where N = ceil(dataSize / packetSize)) are systematic,
 *     meaning they contain the original data directly.
 *   - Packets beyond N are repair symbols generated by the fountain code.
 *   - Recovery requires approximately N + 0.02 packets on average.
 */
final readonly class PacketMetadata
{
    /**
     * Pre-computed CRC32 polynomial table for MPEG-2 variant.
     * Matches the CRC32/MPEG-2 standard used in transport streams.
     */
    private const int CRC32_POLYNOMIAL = 0x04C1_1DB7;

    /**
     * Fixed overhead per packet: 4 bytes Block ID + 4 bytes CRC32.
     */
    public const int HEADER_OVERHEAD_BYTES = 8;

    public function __construct(
        /** Wirehair block identifier (uint32). Determines which coded symbol this packet represents. */
        public int $blockId,

        /** The fountain-coded symbol payload bytes. */
        public string $payload,

        /** CRC32 checksum of (blockId . payload) for integrity verification. */
        public int $checksum,
    ) {}

    /**
     * Create a PacketMetadata from raw block ID and payload, computing the CRC32 automatically.
     */
    public static function fromPayload(int $blockId, string $payload): self
    {
        $data = pack('N', $blockId) . $payload;
        $checksum = crc32($data);

        return new self(
            blockId: $blockId,
            payload: $payload,
            checksum: $checksum,
        );
    }

    /**
     * Serialize this packet into a binary string for embedding into video frames.
     *
     * Wire format:
     *   Bytes 0-3:   Block ID (network byte order, unsigned 32-bit)
     *   Bytes 4-N+3: Payload
     *   Bytes N+4 to N+7: CRC32 (network byte order, unsigned 32-bit)
     */
    public function serialize(): string
    {
        return pack('N', $this->blockId)
             . $this->payload
             . pack('N', $this->checksum);
    }

    /**
     * Deserialize a binary string back into a PacketMetadata instance.
     *
     * @param  string $binary Raw binary packet data.
     * @return self
     *
     * @throws \InvalidArgumentException If the binary data is too short.
     */
    public static function deserialize(string $binary): self
    {
        $minLength = self::HEADER_OVERHEAD_BYTES + 1; // At least 1 byte of payload
        if (strlen($binary) < $minLength) {
            throw new \InvalidArgumentException(
                sprintf('Packet binary too short: %d bytes (minimum %d).', strlen($binary), $minLength),
            );
        }

        // Extract Block ID (first 4 bytes)
        $blockId = unpack('N', substr($binary, 0, 4))[1];

        // Extract CRC32 (last 4 bytes)
        $checksum = unpack('N', substr($binary, -4))[1];

        // Extract payload (everything between Block ID and CRC32)
        $payload = substr($binary, 4, -4);

        return new self(
            blockId: $blockId,
            payload: $payload,
            checksum: $checksum,
        );
    }

    /**
     * Verify the integrity of this packet by recomputing the CRC32.
     *
     * @return bool True if the checksum matches, false if the packet is corrupted.
     */
    public function verifyIntegrity(): bool
    {
        $data = pack('N', $this->blockId) . $this->payload;
        return crc32($data) === $this->checksum;
    }

    /**
     * Get the total serialized size of this packet in bytes.
     */
    public function totalSize(): int
    {
        return self::HEADER_OVERHEAD_BYTES + strlen($this->payload);
    }
}
